export const SECURITY = {
  LOAD_JWT_TOKEN: "LOAD_JWT_TOKEN",
  UPDATE_TOKEN_STATUS: "UPDATE_TOKEN_STATUS",
  DESTROY_JWT_TOKEN: "DESTROY_JWT_TOKEN",
};

export const GLOBAL = {
  START_LOADING: "START_LOADING",
  FINISH_LOADING: "FINISH_LOADING",
};
